** Message: 11:20:12.584: environement.vala:58: Exporting primary_variable
** Message: 11:20:12.584: environement.vala:59: desktop_environnement XDG_CURRENT_DESKTOP
** Message: 11:20:12.584: environement.vala:150: confir_dirs is null, export : /etc/xdg
** Message: 11:20:12.584: environement.vala:184: Exporting XDG_CONFIG_DIRS
** Message: 11:20:12.584: environement.vala:218: custom_data :
** Message: 11:20:12.584: environement.vala:219: data_dirs :/usr/share/fkms:/usr/local/share:/usr/share/raspi-ui-overrides:/usr/share:/usr/share/gdm:/var/lib/menu-xdg
** Message: 11:20:12.584: environement.vala:220: data_dirs not null, export : /usr/share/fkms:/usr/local/share:/usr/share/raspi-ui-overrides:/usr/share:/usr/share/gdm:/var/lib/menu-xdg
** Message: 11:20:12.584: environement.vala:225: Exporting XDG_DATA_DIRS
** Message: 11:20:12.585: utils.vala:138: Config system location : /etc/xdg/lxsession/LXDE-pi
** Message: 11:20:12.586: utils.vala:144: System system path location : /etc/xdg/lxsession/LXDE-pi/desktop.conf
** Message: 11:20:12.586: utils.vala:148: Final file used : /etc/xdg/lxsession/LXDE-pi/desktop.conf
** Message: 11:20:12.586: utils.vala:39: Config system location : /etc/xdg/lxsession/LXDE-pi
** Message: 11:20:12.586: utils.vala:45: System system path location : /etc/xdg/lxsession/LXDE-pi/desktop.conf

** (lxsession:943): WARNING **: 11:20:12.588: utils.vala:70: そのようなファイルやディレクトリはありません
** Message: 11:20:12.589: settings.vala:540: キーファイルにグループ“GTK”のキー“iGtk/ColorScheme”がありません
** Message: 11:20:12.589: settings.vala:540: キーファイルにグループ“Session”のキー“windows_manager/command”がありません
** Message: 11:20:12.589: settings.vala:540: キーファイルにグループ“Session”のキー“panel/command”がありません
** Message: 11:20:12.589: settings.vala:540: キーファイルにグループ“Session”のキー“dock/command”がありません
** Message: 11:20:12.589: settings.vala:540: キーファイルにグループ“Session”のキー“file_manager/command”がありません
** Message: 11:20:12.589: settings.vala:540: キーファイルにグループ“Session”のキー“desktop_manager/command”がありません
** Message: 11:20:12.589: settings.vala:540: キーファイルにグループ“Session”のキー“launcher_manager/autostart”がありません
** Message: 11:20:12.589: settings.vala:540: キーファイルにグループ“Session”のキー“composite_manager/command”がありません
** Message: 11:20:12.589: settings.vala:540: キーファイルにグループ“Session”のキー“im1/command”がありません
** Message: 11:20:12.590: settings.vala:540: キーファイルにグループ“Session”のキー“im2/command”がありません
** Message: 11:20:12.590: settings.vala:540: キーファイルにグループ“Session”のキー“widget1/command”がありません
** Message: 11:20:12.590: settings.vala:540: キーファイルにグループ“Session”のキー“notification/command”がありません
** Message: 11:20:12.590: settings.vala:540: キーファイルにグループ“Session”のキー“keybindings/command”がありません
** Message: 11:20:12.590: settings.vala:540: キーファイルにグループ“Session”のキー“im_manager/command”がありません
** Message: 11:20:12.590: settings.vala:540: キーファイルにグループ“Session”のキー“screensaver/command”がありません
** Message: 11:20:12.590: settings.vala:540: キーファイルにグループ“Session”のキー“power_manager/command”がありません
** Message: 11:20:12.590: settings.vala:540: キーファイルにグループ“Session”のキー“audio_manager/command”がありません
** Message: 11:20:12.590: settings.vala:540: キーファイルにグループ“Session”のキー“workspace_manager/command”がありません
** Message: 11:20:12.591: settings.vala:540: キーファイルにグループ“Session”のキー“screenshot_manager/command”がありません
** Message: 11:20:12.591: settings.vala:540: キーファイルにグループ“Session”のキー“message_manager/command”がありません
** Message: 11:20:12.591: settings.vala:540: キーファイルにグループ“Session”のキー“upgrade_manager/command”がありません
** Message: 11:20:12.591: settings.vala:540: キーファイルにグループ“Session”のキー“updates_manager/command”がありません
** Message: 11:20:12.591: settings.vala:540: キーファイルにグループ“Session”のキー“updates_manager/timeout”がありません
** Message: 11:20:12.591: settings.vala:540: キーファイルにグループ“Session”のキー“crash_manager/command”がありません
** Message: 11:20:12.591: settings.vala:540: キーファイルにグループ“Session”のキー“crash_manager/dev_mode”がありません
** Message: 11:20:12.591: settings.vala:540: キーファイルにグループ“Session”のキー“crash_manager/timeout”がありません
** Message: 11:20:12.591: settings.vala:540: キーファイルにグループ“Session”のキー“upstart_user_session”がありません
** Message: 11:20:12.592: settings.vala:540: キーファイルにグループ“Session”のキー“proxy_manager/http”がありません
** Message: 11:20:12.592: settings.vala:540: キーファイルにグループ“Session”のキー“a11y/command”がありません
** Message: 11:20:12.592: settings.vala:540: キーファイルにグループ“Session”のキー“xrandr/command”がありません
** Message: 11:20:12.592: settings.vala:540: キーファイルにグループ“Session”のキー“network_gui/command”がありません
** Message: 11:20:12.592: settings.vala:540: キーファイルにグループ“Session”のキー“webbrowser/command”がありません
** Message: 11:20:12.592: settings.vala:540: キーファイルにグループ“Session”のキー“email/command”がありません
** Message: 11:20:12.592: settings.vala:540: キーファイルにグループ“Session”のキー“pdf_reader/command”がありません
** Message: 11:20:12.593: settings.vala:540: キーファイルにグループ“Session”のキー“video_player/command”がありません
** Message: 11:20:12.593: settings.vala:540: キーファイルにグループ“Session”のキー“audio_player/command”がありません
** Message: 11:20:12.593: settings.vala:540: キーファイルにグループ“Session”のキー“image_display/command”がありません
** Message: 11:20:12.593: settings.vala:540: キーファイルにグループ“Session”のキー“text_editor/command”がありません
** Message: 11:20:12.593: settings.vala:540: キーファイルにグループ“Session”のキー“archive/command”がありません
** Message: 11:20:12.593: settings.vala:540: キーファイルにグループ“Session”のキー“charmap/command”がありません
** Message: 11:20:12.593: settings.vala:540: キーファイルにグループ“Session”のキー“calculator/command”がありません
** Message: 11:20:12.593: settings.vala:540: キーファイルにグループ“Session”のキー“spreadsheet/command”がありません
** Message: 11:20:12.593: settings.vala:540: キーファイルにグループ“Session”のキー“bittorent/command”がありません
** Message: 11:20:12.593: settings.vala:540: キーファイルにグループ“Session”のキー“document/command”がありません
** Message: 11:20:12.594: settings.vala:540: キーファイルにグループ“Session”のキー“webcam/command”がありません
** Message: 11:20:12.594: settings.vala:540: キーファイルにグループ“Session”のキー“burn/command”がありません
** Message: 11:20:12.594: settings.vala:540: キーファイルにグループ“Session”のキー“notes/command”がありません
** Message: 11:20:12.594: settings.vala:540: キーファイルにグループ“Session”のキー“disk_utility/command”がありません
** Message: 11:20:12.594: settings.vala:540: キーファイルにグループ“Session”のキー“tasks/command”がありません
** Message: 11:20:12.594: settings.vala:540: キーファイルにグループ“Keymap”がありません
** Message: 11:20:12.594: settings.vala:540: キーファイルにグループ“State”のキー“laptop_mode”がありません
** Message: 11:20:12.594: settings.vala:540: キーファイルにグループ“Dbus”のキー“gnome”がありません
** Message: 11:20:12.594: settings.vala:540: キーファイルにグループ“Environment”のキー“type”がありません
** Message: 11:20:12.595: settings.vala:540: キーファイルにグループ“Environment”のキー“ubuntu_menuproxy”がありません
** Message: 11:20:12.595: settings.vala:540: キーファイルにグループ“Environment”のキー“toolkit_integration”がありません
** Message: 11:20:12.595: settings.vala:540: キーファイルにグループ“Environment”のキー“gtk/overlay_scrollbar_disable”がありません
** Message: 11:20:12.595: settings.vala:540: キーファイルにグループ“Environment”のキー“qt/force_theme”がありません
** Message: 11:20:12.595: settings.vala:540: キーファイルにグループ“Environment”のキー“qt/platform”がありません
** Message: 11:20:12.596: settings.vala:462: Monitoring: /etc/xdg/lxsession/LXDE-pi/desktop.conf
** Message: 11:20:12.596: settings.vala:470: Desktop file is not in config home, monitoring creation of it
** Message: 11:20:12.597: settings.vala:485: Monitoring home path: /home/raspi4-01/.config/lxsession/LXDE-pi/desktop.conf
** Message: 11:20:12.597: environement.vala:79: Exporting variable
** Message: 11:20:12.597: environement.vala:80: desktop_environnement XDG_CURRENT_DESKTOP
** Message: 11:20:12.597: environement.vala:177: custom_config :
** Message: 11:20:12.598: environement.vala:178: config_dirs :/etc/xdg
** Message: 11:20:12.598: environement.vala:179: confir_dirs not null, export : /etc/xdg
** Message: 11:20:12.598: environement.vala:184: Exporting XDG_CONFIG_DIRS
** Message: 11:20:12.598: environement.vala:218: custom_data :
** Message: 11:20:12.598: environement.vala:219: data_dirs :/usr/share/fkms:/usr/local/share:/usr/share/raspi-ui-overrides:/usr/share:/usr/share/gdm:/var/lib/menu-xdg
** Message: 11:20:12.598: environement.vala:220: data_dirs not null, export : /usr/share/fkms:/usr/local/share:/usr/share/raspi-ui-overrides:/usr/share:/usr/share/gdm:/var/lib/menu-xdg
** Message: 11:20:12.598: environement.vala:225: Exporting XDG_DATA_DIRS
** Message: 11:20:12.598: utils.vala:39: Config system location : /etc/xdg/lxsession/LXDE-pi
** Message: 11:20:12.598: utils.vala:45: System system path location : /etc/xdg/lxsession/LXDE-pi/desktop.conf

** (lxsession:943): WARNING **: 11:20:12.599: utils.vala:70: そのようなファイルやディレクトリはありません
** Message: 11:20:12.599: environement.vala:254: No entry in [Environment_variable]. キーファイルにグループ“Environment_variable”がありません

** (lxsession:943): WARNING **: 11:20:12.604: process.vala:49: 子プロセス“xprop”の起動に失敗しました (そのようなファイルやディレクトリはありません)

** (lxsession:943): WARNING **: 11:20:12.604: process.vala:50: Error when launching xprop
** Message: 11:20:12.605: utils.vala:138: Config system location : /etc/xdg/lxsession/LXDE-pi
** Message: 11:20:12.605: utils.vala:144: System system path location : /etc/xdg/lxsession/LXDE-pi/conffiles.conf
** Message: 11:20:12.605: utils.vala:148: Final file used : /etc/xdg/lxsession/LXDE-pi/conffiles.conf
** Message: 11:20:12.605: options.vala:164: Activate xsettings_manager build-in
** Message: 11:20:12.605: utils.vala:39: Config system location : /etc/xdg/lxsession/LXDE-pi
** Message: 11:20:12.605: utils.vala:45: System system path location : /etc/xdg/lxsession/LXDE-pi/desktop.conf

** (lxsession:943): WARNING **: 11:20:12.606: utils.vala:70: そのようなファイルやディレクトリはありません
** Message: 11:20:12.629: app.vala:728: polkit separate
** Message: 11:20:12.630: app.vala:728: polkit separate
** Message: 11:20:12.641: app.vala:76: Launching lxpolkit 
** Message: 11:20:12.642: utils.vala:138: Config system location : /etc/xdg/lxsession/LXDE-pi
** Message: 11:20:12.642: utils.vala:144: System system path location : /etc/xdg/lxsession/LXDE-pi/autostart
** Message: 11:20:12.642: utils.vala:148: Final file used : /etc/xdg/lxsession/LXDE-pi/autostart
** Message: 11:20:12.642: autostart.vala:42: Autostart path : /etc/xdg/lxsession/LXDE-pi/autostart
** Message: 11:20:12.665: app.vala:76: Launching lxpanel 
** Message: 11:20:12.678: app.vala:76: Launching pcmanfm 

** (lxsession:943): WARNING **: 11:20:12.683: app.vala:86: 子プロセス“xscreensaver”の起動に失敗しました (そのようなファイルやディレクトリはありません)

** (lxsession:943): WARNING **: 11:20:12.683: app.vala:87: Error when launching xscreensaver
** Message: 11:20:12.696: options.vala:107: Create build-in Clipboard
** Message: 11:20:12.698: main.vala:450: Check keymap_mode (null)
** Message: 11:20:12.702: app.vala:76: Launching /usr/bin/ssh-agent 
SSH_AUTH_SOCK=/tmp/ssh-TKOhK4iVSuKJ/agent.1105; export SSH_AUTH_SOCK;
SSH_AGENT_PID=1114; export SSH_AGENT_PID;
echo Agent pid 1114;
** Message: 11:20:13.183: app.vala:130: /usr/bin/ssh-agent exit with this type of exit: 0
Openbox-Message: 正当なメニューファイル"/usr/share/lxde/openbox/menu.xml"を見つけることができません。
** Message: 11:20:14.389: x-terminal-emulator has very limited support, consider choosing another terminal

** (pcmanfm:1101): WARNING **: 11:20:14.393: The directory '/home/raspi4-01/Templates' doesn't exist, ignoring it
** Message: 11:20:14.659: x-terminal-emulator has very limited support, consider choosing another terminal

** (lxpanel:1100): WARNING **: 11:20:14.664: The directory '/home/raspi4-01/Templates' doesn't exist, ignoring it
** Message: 11:20:16.476: netman: network manager service not running; plugin hidden
** Message: 11:20:16.527: Connecting ...
** Message: 11:20:16.527: Status changed to down

** (lxpanel:1100): CRITICAL **: 11:20:16.528: dhcpcd_open: デバイスに対する不適切なioctlです
** Message: 11:20:16.783: ptbatt: battery 0 not found
** Message: 11:20:17.477: up: No network connection - polling...
** Message: 11:20:17.529: Status changed to opened
** Message: 11:20:17.529: Connected to dhcpcd-8.1.2
** Message: 11:20:17.530: Status changed to disconnected
** Message: 11:20:17.530: eth0: Link is down
** Message: 11:20:17.530: wlan0: Not associated
** Message: 11:20:17.533: wlan0: WPA status connected
** Message: 11:20:25.588: eth0: Link is up, configuring
** Message: 11:20:25.588: Status changed to connecting
** Message: 11:20:30.997: eth0: Configured 172.22.5.201/16
** Message: 11:20:30.997: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 11 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 13 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 15 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 14:52:25.848: up: Checking for updates
** Message: 14:52:44.030: up: Cache updated - comparing versions
** Message: 14:52:59.391: up: Check complete - 101 updates available
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 21 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 14:55:10.150: eth0: Link is down
** Message: 14:55:10.151: Status changed to disconnected
** Message: 14:55:45.032: eth0: Link is up, configuring
** Message: 14:55:45.032: Status changed to connecting
** Message: 14:55:46.143: eth0: Link is down
** Message: 14:55:46.144: Status changed to disconnected
** Message: 14:55:47.273: eth0: Link is up, configuring
** Message: 14:55:47.274: Status changed to connecting
** Message: 14:55:52.414: eth0: Configured 172.22.5.201/16
** Message: 14:55:52.414: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 23 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 14:57:11.686: eth0: Link is down
** Message: 14:57:11.686: Status changed to disconnected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 29 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 14:57:46.997: eth0: Link is up, configuring
** Message: 14:57:46.998: Status changed to connecting
** Message: 14:57:52.376: eth0: Configured 172.22.5.201/16
** Message: 14:57:52.376: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 31 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 15:02:24.518: eth0: Link is down
** Message: 15:02:24.519: Status changed to disconnected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 37 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 15:03:26.323: eth0: Link is up, configuring
** Message: 15:03:26.323: Status changed to connecting
** Message: 15:03:31.745: eth0: Configured 172.22.5.201/16
** Message: 15:03:31.745: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 39 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 45 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 15:06:55.156: eth0: Link is down
** Message: 15:06:55.157: Status changed to disconnected
** Message: 15:07:36.776: eth0: Link is up, configuring
** Message: 15:07:36.777: Status changed to connecting
** Message: 15:07:42.175: eth0: Configured 172.22.5.201/16
** Message: 15:07:42.176: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 47 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 15:10:30.794: eth0: Link is down
** Message: 15:10:30.795: Status changed to disconnected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 53 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 15:11:33.483: eth0: Link is up, configuring
** Message: 15:11:33.483: Status changed to connecting
** Message: 15:11:37.865: eth0: Configured 172.22.5.201/16
** Message: 15:11:37.866: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 55 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 61 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 15:17:59.080: eth0: Link is down
** Message: 15:17:59.081: Status changed to disconnected
** Message: 15:18:34.181: eth0: Link is up, configuring
** Message: 15:18:34.182: Status changed to connecting
** Message: 15:18:38.714: eth0: Configured 172.22.5.201/16
** Message: 15:18:38.715: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 63 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 15:25:38.751: eth0: Link is down
** Message: 15:25:38.752: Status changed to disconnected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 69 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 15:26:55.413: eth0: Link is up, configuring
** Message: 15:26:55.414: Status changed to connecting
** Message: 15:27:00.435: eth0: Configured 172.22.5.201/16
** Message: 15:27:00.436: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 71 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 15:31:37.905: eth0: Link is down
** Message: 15:31:37.905: Status changed to disconnected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 77 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 15:32:20.893: eth0: Link is up, configuring
** Message: 15:32:20.893: Status changed to connecting
** Message: 15:32:26.020: eth0: Configured 172.22.5.201/16
** Message: 15:32:26.020: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 79 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 85 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 15:33:29.101: eth0: Link is down
** Message: 15:33:29.101: Status changed to disconnected
** Message: 15:34:01.845: eth0: Link is up, configuring
** Message: 15:34:01.846: Status changed to connecting
** Message: 15:34:06.885: eth0: Configured 172.22.5.201/16
** Message: 15:34:06.885: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 87 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 15:34:56.433: eth0: Link is down
** Message: 15:34:56.434: Status changed to disconnected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 93 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 15:37:12.163: eth0: Link is up, configuring
** Message: 15:37:12.163: Status changed to connecting
** Message: 15:37:17.867: eth0: Configured 172.22.5.201/16
** Message: 15:37:17.868: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 95 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 101 was not found when attempting to remove it
  GLib.source_remove (self.timer)

(pcmanfm:1101): Gtk-WARNING **: 15:38:12.460: Theme parsing error: <data>:2:27: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

(pcmanfm:1101): Gtk-WARNING **: 15:38:12.460: Theme parsing error: <data>:3:30: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(pcmanfm:1101): Gtk-WARNING **: 15:38:43.739: gtk_menu_detach(): menu is not attached

(pcmanfm:1101): Gtk-WARNING **: 15:38:51.327: gtk_menu_detach(): menu is not attached
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 104 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 15:39:50.637: eth0: Link is down
** Message: 15:39:50.638: Status changed to disconnected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 106 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 15:40:37.973: eth0: Link is up, configuring
** Message: 15:40:37.974: Status changed to connecting
** Message: 15:40:42.729: eth0: Configured 172.22.5.201/16
** Message: 15:40:42.730: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 108 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 114 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 117 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 119 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 15:56:57.954: eth0: Link is down
** Message: 15:56:57.955: Status changed to disconnected
** Message: 15:57:07.633: eth0: Link is up, configuring
** Message: 15:57:07.634: Status changed to connecting
** Message: 15:57:09.573: eth0: Link is down
** Message: 15:57:09.574: Status changed to disconnected
** Message: 15:57:11.093: eth0: Link is up, configuring
** Message: 15:57:11.094: Status changed to connecting
** Message: 15:57:16.196: eth0: Configured 172.22.5.201/16
** Message: 15:57:16.197: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 121 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 127 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 16:31:38.277: eth0: Link is down
** Message: 16:31:38.278: Status changed to disconnected
** Message: 16:32:33.433: eth0: Link is up, configuring
** Message: 16:32:33.433: Status changed to connecting
** Message: 16:32:38.889: eth0: Configured 172.22.5.201/16
** Message: 16:32:38.889: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 129 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 16:37:56.811: eth0: Link is down
** Message: 16:37:56.812: Status changed to disconnected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 135 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 16:38:34.773: eth0: Link is up, configuring
** Message: 16:38:34.773: Status changed to connecting
** Message: 16:38:39.972: eth0: Configured 172.22.5.201/16
** Message: 16:38:39.973: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 137 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 143 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 16:41:37.172: eth0: Link is down
** Message: 16:41:37.173: Status changed to disconnected
** Message: 16:42:14.883: eth0: Link is up, configuring
** Message: 16:42:14.883: Status changed to connecting
** Message: 16:42:20.788: eth0: Configured 172.22.5.201/16
** Message: 16:42:20.788: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 145 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 151 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 16:42:44.970: eth0: Link is down
** Message: 16:42:44.971: Status changed to disconnected
** Message: 16:43:15.313: eth0: Link is up, configuring
** Message: 16:43:15.313: Status changed to connecting
** Message: 16:43:20.214: eth0: Configured 172.22.5.201/16
** Message: 16:43:20.215: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 153 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 16:43:41.469: eth0: Link is down
** Message: 16:43:41.470: Status changed to disconnected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 159 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 16:43:54.813: eth0: Link is up, configuring
** Message: 16:43:54.814: Status changed to connecting
** Message: 16:44:00.182: eth0: Configured 172.22.5.201/16
** Message: 16:44:00.182: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 161 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 167 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 16:47:00.929: eth0: Link is down
** Message: 16:47:00.929: Status changed to disconnected
** Message: 16:48:46.413: eth0: Link is up, configuring
** Message: 16:48:46.413: Status changed to connecting
** Message: 16:48:51.811: eth0: Configured 172.22.5.201/16
** Message: 16:48:51.811: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 169 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 175 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 16:50:37.912: eth0: Link is down
** Message: 16:50:37.913: Status changed to disconnected
** Message: 16:51:05.933: eth0: Link is up, configuring
** Message: 16:51:05.933: Status changed to connecting
** Message: 16:51:10.679: eth0: Configured 172.22.5.201/16
** Message: 16:51:10.679: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 177 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 16:51:46.374: eth0: Link is down
** Message: 16:51:46.375: Status changed to disconnected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 183 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 16:52:43.983: eth0: Link is up, configuring
** Message: 16:52:43.983: Status changed to connecting
** Message: 16:52:49.160: eth0: Configured 172.22.5.201/16
** Message: 16:52:49.161: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 185 was not found when attempting to remove it
  GLib.source_remove (self.timer)
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 191 was not found when attempting to remove it
  GLib.source_remove (self.timer)
** Message: 16:57:33.945: eth0: Link is down
** Message: 16:57:33.946: Status changed to disconnected
** Message: 16:58:08.733: eth0: Link is up, configuring
** Message: 16:58:08.734: Status changed to connecting
** Message: 16:58:14.188: eth0: Configured 172.22.5.201/16
** Message: 16:58:14.188: Status changed to connected
/usr/share/system-config-printer/applet.py:364: Warning: Source ID 193 was not found when attempting to remove it
  GLib.source_remove (self.timer)
